# https://alacritty.org/config-alacritty.html
# config helper

general.live_config_reload = true
terminal.shell = "/usr/bin/zsh"

[window]
decorations = "Full"
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 4

[font]
normal = { family = "Fira Code Nerd Font Propo", style = "Regular" }
bold = { family = "Fira Code Nerd Font Propo", style = "Medium" }
italic = { family = "Fira Code Nerd Font Propo", style = "Light" }
size = 10
# size = 8

[bell]
duration = 0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_timeout = 0
