import = [
  "~/git/dotfiles/.config/alacritty/catppuccin-frappe.toml"
]

live_config_reload = true
shell = "/usr/bin/zsh"

[window]
decorations = "None"
opacity = 0.95
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 4

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Medium" }
italic = { family = "Fira Code", style = "Light" }
size = 8

[bell]
duration = 0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_timeout = 0
