# https://alacritty.org/config-alacritty.html
# config helper
#
# https://github.com/alacritty/alacritty-theme?tab=readme-ov-file
# Alacritty themes

import = [
#  "~/git/dotfiles/.config/alacritty/catppuccin-frappe.toml"
#  "~/git/dotfiles/.config/alacritty/rose-pine.toml"
]

live_config_reload = true
shell = "/usr/bin/zsh"
# shell = "/usr/bin/pwsh"

[window]
decorations = "None"
startup_mode = "Maximized"

[scrolling]
history = 100000
multiplier = 4

[font]
normal = { family = "Fira Code Nerd Font Propo", style = "Regular" }
bold = { family = "Fira Code Nerd Font Propo", style = "Medium" }
italic = { family = "Fira Code Nerd Font Propo", style = "Light" }
size = 8

[bell]
duration = 0

[cursor]
style = { shape = "Block", blinking = "On" }
blink_timeout = 0
